### ISSUE TITLE
Symmetric difference causes extra vertices

### ISSUE THREAD

**Issue by Smibu** [Smibu/elmanager#120]
In GitLab by @Smibu on Feb 5, 2018, 22:58

See dani's screenshot:

![image](https://user-images.githubusercontent.com/7945133/71770606-34935900-2f37-11ea-9d99-5932cedeb893.png)

**Comment by alistaircarscadden** [comment]
Is this fixed? I don't see this behaviour anymore

**Comment by Smibu** [comment]
You're right, I fixed this last year, but forgot to close.
