### ISSUE TITLE
Using transform tool without selection causes error

### ISSUE THREAD

**Issue by alistaircarscadden** [Smibu/elmanager#132]
When using the transform tool (space) without a selection you will get an DivideByZero error you cannot continue from, only quit.

Only occurs when no previous selection was made. So, if you select a polygon, and unselect it, then use spacebar, no error happens.

**Comment by alistaircarscadden** [comment]
Using the debug tool it seems that in TransformTool.cs on line 169

```
public void MouseDown(MouseEventArgs mouseData)
        ...
                for (i = 0; i < 4; i++)
                {
                    if ((_transformRectangle[i] - CurrentPos).Length <
                        Global.AppSettings.LevelEditor.CaptureRadius * Renderer.ZoomLevel)
                    {
```

`_transformRectangle` is null

**Comment by Smibu** [comment]
Fixed in https://github.com/Smibu/elmanager/pull/133.
