### ISSUE TITLE
After zooming out using 'Zoom' and right clicking, hotkeys to choose other tools (for example S for 'Select') do not work because of the context menu that appears

### ISSUE THREAD

**Issue by alistaircarscadden** [Smibu/elmanager#151]
Which makes the 'Zoom' tool pretty unfriendly for hotkeying

**Comment by Smibu** [comment]
Ah, I've noticed the same bug, but didn't pay much attention to it because I thought no one uses Zoom tool anyway because of mouse wheel.

Just wondering - what was your use case, I mean why did you use Zoom tool instead of mouse wheel?

But yeah, I should fix this in any case :)

**Comment by alistaircarscadden** [comment]
My mouse wheel is broken so I've started using all sorts of different things in different programs to replace it.

**Comment by Smibu** [comment]
Zoom button was recently removed -> closing. A new issue can be opened if the need to zoom without mouse wheel comes up again. Most likely it should be some keyboard shortcut instead of a separate tool.
