### ISSUE TITLE
Unhandled exception when moving polygon while test playing

### ISSUE THREAD

**Issue by SjurdurS** [Smibu/elmanager#154]
I keep getting an "Unhandled exception" error: "Object reference not set to an instance of an object" when moving polygons after having test played a level.

![image](https://github.com/Smibu/elmanager/assets/5624291/07f40c62-25e6-43fe-ac03-1281e1ee0c39)

Steps to reproduce:
1. Create a new level.
2. Add a triangle under start position
3. Press play
4. Move the triangle while bike is moving

See video for reference:
https://github.com/Smibu/elmanager/assets/5624291/32b831f2-0b0d-4381-b307-49ba48adf5fd

**Comment by Smibu** [comment]
Thanks, fixed in beta.
