### ISSUE TITLE
Add option to lock grid

### ISSUE THREAD

**Issue by SjurdurS** [Smibu/elmanager#155]
I've been using the grid a bit, but I keep finding myself zooming the grid using Ctrl+Mouse wheel scroll.
It is hard to reposition the grid to the previous position (ctrl+z) does not affect grid zoom/position.

It would be nice if it was possible to lock the grid to current position.
Furthermore, as an extension to this, it would also be nice if it was possible to position the grid to a specific point.

**Comment by Smibu** [comment]
Ctrl + press and hold mouse wheel + drag allows you to move the grid. Does this help?

But yes, grid undo/lock could be a useful addition.

**Comment by SjurdurS** [comment]
I made a quick fix, but I can't make a pull request. Not sure if you allow outside contributors or how you would like a pull request.

Here is a patch:

Subject: [PATCH] Add Lock Grid rendering setting

Introduce a new rendering setting to disable the ability to move and resize the grid.
---
 Elmanager/LevelEditor/LevelEditorForm.cs | 4 ++--
 Elmanager/Rendering/RenderingSettings.cs | 3 +++
 2 files changed, 5 insertions(+), 2 deletions(-)

diff --git a/Elmanager/LevelEditor/LevelEditorForm.cs b/Elmanager/LevelEditor/LevelEditorForm.cs
index 405c042..75caced 100644
--- a/Elmanager/LevelEditor/LevelEditorForm.cs
+++ b/Elmanager/LevelEditor/LevelEditorForm.cs
@@ -1495,7 +1495,7 @@ internal partial class LevelEditorForm : FormMod, IMessageFilter
         if (_draggingScreen || _draggingGrid)
         {
             Vector z = GetMouseCoordinates();
-            if (_draggingGrid)
+            if (!Settings.RenderingSettings.LockGrid && _draggingGrid)
             {
                 _sceneSettings.GridOffset = _gridStartOffset + _moveStartPosition - z;
             }
@@ -1521,7 +1521,7 @@ internal partial class LevelEditorForm : FormMod, IMessageFilter
 
     private void MouseWheelZoom(long delta)
     {
-        if (Keyboard.IsKeyDown(Key.LeftCtrl))
+        if (!Settings.RenderingSettings.LockGrid && Keyboard.IsKeyDown(Key.LeftCtrl))
         {
             double currSize = Settings.RenderingSettings.GridSize;
             double newSize = currSize + Math.Sign(delta) * _zoomCtrl.Cam.ZoomLevel / 50.0;
diff --git a/Elmanager/Rendering/RenderingSettings.cs b/Elmanager/Rendering/RenderingSettings.cs
index 5f98d2d..d87113d 100644
--- a/Elmanager/Rendering/RenderingSettings.cs
+++ b/Elmanager/Rendering/RenderingSettings.cs
@@ -201,6 +201,9 @@ internal class RenderingSettings
         }
     }
 
+    [DisplayName("Lock Grid")]
+    public bool LockGrid { get; set; }
+
     [DisplayName("Line width")]
     public float LineWidth
     {
--

**Comment by Smibu** [comment]
Thanks :) yes pull requests are welcome, I think you just need to fork the repo first. I see you don't have any (public) forks in GitHub yet.

I would add the setting under LevelEditorSettings because it's more about lev editor behavior rather than rendering. Otherwise looks fine at first glance.

**Comment by Smibu** [comment]
Done in https://github.com/Smibu/elmanager/pull/156
